### ISSUE TITLE
Rollback not working

### ISSUE THREAD

**Issue by Joshuak52** [Ghost-chu/CoreProtectTNT#19]
**Version:**
CoreProtectTNT version 2.3.1

**description:**
I explode something using tnt or end crystal, it correctly shows in /co inspect but if I did /co rollback <player> it does not roll back broken blocks from the explosion. It does however rollback their broken by hand blocks.

**Comment by Ghost-chu** [comment]
Unfortunately, this project has been abandon.
Please switch to [Prism](https://www.spigotmc.org/resources/prism.99397/), which has all the features of CoreProtect + CoreProtectTNT.
